### ISSUE TITLE
[IMPROVEMENT] Add previews on all views

### ISSUE THREAD

**Issue by emin-grbo** [roblack/swiftUIViews#7]
**Is your improvement request related to a problem? Please describe.**
no previews on views

**Describe the solution you'd like**
add previews based on @mariob suggestion

**Comment by mariob** [comment]
Tell me if you need help to share the work

**Comment by emin-grbo** [comment]
@mariob Tnx man! I kinda didn't wanna bother you with this legwork and it required some changes in other parts of the code. You could delete all "top" views if you wanna? Since previews would replace these and no need for them really.
Then i need to do some design work and play with colors a bit, i want to make it so you have light and dark mode variants for some views, not only "neumorph button" :)
